### ISSUE TITLE
오타 리포트

### ISSUE THREAD

**Issue by inf0craw1** [xvzc/boj-cli#13]
안녕하세요.

사소한 오타 하나 찾아서 제보합니다! 😄

https://github.com/xvzc/boj-cli/blob/82463f3fa9bfd8a2603b564e84abf3ed37da8d14/README.md?plain=1#L33
```config.yaml```로 수정되어야 할 것 같아요!

잘 사용하고 있습니다. 감사합니다!

**Comment by xvzc** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ PR 날려주십쇼
