### ISSUE TITLE
[fix] 테스트케이스 내부 이스케이프 문자 처리 에러

### ISSUE THREAD

**Issue by kimhxsong** [xvzc/boj-cli#20]
백준 단계별[1]  10171번 문제를 풀이하다가 발견하였습니다.  
테스트 케이스 입출력 문자열에 이스케이프 문자가 포함되는 경우는 굉장히 드물지만, 처리해주시면 좀 더 완성도 높은 툴이 될 것 같습니다 :) 

<img width="1392" alt="image" src="https://github.com/xvzc/boj-cli/assets/83186385/c4982fe3-7472-4082-986b-f1732bdf4a0a">

**Comment by xvzc** [comment]
안녕하세요. 가까운 시일 내에 toml 포멧의 테스트케이스 저장 방식을 txt 파일 방식으로 전환할 예정입니다. 해당 부분이 배포되면 고쳐질 것 같습니다. 의견 감사드립니다.

**Comment by xvzc** [comment]
최신 릴리즈에서 해결되었습니다.
