### ISSUE TITLE
macOS에서 CRLF가 포함된 테스트 케이스를 오답으로 인식하는 문제

### ISSUE THREAD

**Issue by endixk** [xvzc/boj-cli#6]
안녕하세요,

먼저 PS를 윤택하게 만들어 줄 유용한 툴을 개발해주심에 감사드립니다!

macOS에서 프로그램을 사용 중 한 가지 문제가 있어 제보합니다.

아래 첨부한 이미지와 같이 macOS에서 텍스트가 포함된 예제를 `boj init` 할 경우 CRLF가 포함된 테스트 케이스 파일이 생성되는데,

<img width="641" alt="Screenshot 2023-09-29 at 22 49 05" src="https://github.com/xvzc/boj-cli/assets/49298377/bd321b72-64c8-48c9-9836-830583a2cd53">

이를 `boj run` 하면 오답으로 인식하는 문제가 있습니다. 같은 코드를 `boj submit`할 경우 AC를 받습니다.

테스트 케이스 파일의 CRLF를 LF로 바꾸어주고 `boj run`을 돌리면 PASSED가 출력되는 것을 확인하였습니다.

OS에 맞게 테스트 케이스를 준비해주는 방향으로 개선이 되면 좋을 것 같다는 의견 드립니다!

**Comment by xvzc** [comment]
의견 감사드립니다. 최대한 빠른 시일내에 해결방안이 있는지 알아볼께요! 😀

**Comment by xvzc** [comment]
@endixk 해당 이슈 해결된 `0.1.8` 버젼 배포되었습니다.

**Comment by endixk** [comment]
빠른 업데이트 감사합니다!
